# -*- coding: utf-8 -*-
from odoo import models, fields, api


class AccountMove(models.Model):
    _inherit = 'account.move'

    l10n_mx_edi_imported_from_xml = fields.Boolean(
        string='Imported from XML',
        default=False,
        readonly=True,
        copy=False,
        help='If this field is active, the CFDI was imported from its XML file.')
    l10n_mx_edi_sign_required = fields.Boolean(
        string='Sign Invoice?',
        default=True,
        copy=False,
        help='If this field is active, the CFDI will be generated for this invoice.')
    l10n_mx_edi_payment_sign_required = fields.Boolean(
        string='Sign CFDI Payment?',
        default=True,
        copy=False,
        help='If this field is active, the CFDI payment will be generated for this invoice.')
    l10n_mx_edi_external_reference = fields.Char(
        string='External Reference',
        copy=False,
        help='External Invoice Reference comes normally in the PDF, it was generated by the'
        ' External Partner who signed the invoice.')
    l10n_mx_edi_usage = fields.Selection(
        selection_add=[('S01', 'No tax effects')])

    @api.depends('move_type', 'company_currency_id', 'payment_id', 'statement_line_id')
    def _compute_l10n_mx_edi_is_cfdi_needed(self):
        """ Check whatever or not the CFDI is needed on this invoice.
        """
        for move in self:
            move.l10n_mx_edi_is_cfdi_needed = \
                move.country_code == 'MX' \
                and move.l10n_mx_edi_sign_required \
                and move.company_currency_id.name == 'MXN' \
                and (move.move_type in ('out_invoice', 'out_refund') or move._l10n_mx_edi_is_cfdi_payment())


class AccountMoveLine(models.Model):
    _inherit = "account.move.line"

    @api.onchange('product_id')
    def _inverse_product_id(self):
        for line in self:
            if not line.move_id.l10n_mx_edi_imported_from_xml:
                super(AccountMoveLine, line)._inverse_product_id()

    @api.depends('product_id', 'product_uom_id')
    def _compute_price_unit(self):
        for line in self:
            if not line.move_id.l10n_mx_edi_imported_from_xml:
                super(AccountMoveLine, line)._compute_price_unit()

    @api.depends('product_id', 'journal_id')
    def _compute_name(self):
        for line in self:
            if not line.move_id.l10n_mx_edi_imported_from_xml:
                super(AccountMoveLine, line)._compute_name()

    @api.depends('product_id', 'product_uom_id')
    def _compute_tax_ids(self):
        for line in self:
            if not line.move_id.l10n_mx_edi_imported_from_xml:
                super(AccountMoveLine, line)._compute_tax_ids()
